# Generated by Django 2.0.7 on 2018-07-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.TextField()),
                ('cleaved', models.TextField()),
                ('purified', models.TextField()),
                ('AAA', models.TextField()),
                ('totalProjects', models.TextField()),
            ],
        ),
    ]
